# Generated by Django 2.0 on 2018-06-24 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abastecer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha_creacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('fecha_creacion', models.DateField()),
                ('descripcion', models.TextField(max_length=400)),
                ('precio_Compra', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('stock', models.PositiveSmallIntegerField()),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.Categoria')),
            ],
        ),
        migrations.AddField(
            model_name='abastecer',
            name='medicamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.Medicamento'),
        ),
    ]
