# Generated by Django 2.0 on 2018-06-24 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Abastecer',
            new_name='Abastecimiento',
        ),
        migrations.RenameField(
            model_name='abastecimiento',
            old_name='fecha_creacion',
            new_name='fecha_abastecimiento',
        ),
    ]
