# Generated by Django 2.0.6 on 2018-06-15 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_medicamento_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicamento',
            old_name='fecha_expiracion',
            new_name='f_creacion',
        ),
        migrations.RenameField(
            model_name='medicamento',
            old_name='fecha_produccion',
            new_name='f_produccion',
        ),
        migrations.RenameField(
            model_name='medicamento',
            old_name='precio_Compra',
            new_name='p_Compra',
        ),
        migrations.RenameField(
            model_name='medicamento',
            old_name='precio_venta',
            new_name='p_venta',
        ),
    ]
