# Generated by Django 2.0.6 on 2018-06-15 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20180615_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicamento',
            old_name='f_creacion',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='medicamento',
            old_name='p_Compra',
            new_name='precio_Compra',
        ),
        migrations.RenameField(
            model_name='medicamento',
            old_name='p_venta',
            new_name='precio_venta',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='f_produccion',
        ),
    ]
